[package]
name = "libwasmrun_wast"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wast_lexer"
path = "bin/wast_lexer.rs"

[dependencies]
lexgen = { git = "https://github.com/osa1/lexgen", rev = "271ba43" }
lexgen_util = { git = "https://github.com/osa1/lexgen", rev = "271ba43" }
