[package]
name = "wasmrun"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
fxhash = "0.2"
parity-wasm = "0.42"

[build-dependencies]
rustc_tools_util = "0.2.0"

[profile.release]
lto = true
codegen-units = 1
