[workspace]
resolver = "2"
members = [
    "crates/libwasmrun",
    "crates/libwasmrun_syntax",
    "crates/libwasmrun_wast",
    "crates/spec-test",
    "crates/w4wr",
    "crates/wasi-test",
    "crates/wasmrun",
]

exclude = [
    "tests/wasi"
]

[profile.release]
lto = true
codegen-units = 1
