[package]
name = "libwasmrun"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2"
parity-wasm = { version = "0.42", features = ["multi_value"] }
