[package]
name = "wasmrun"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2.33"
libwasmrun = { path = "../libwasmrun" }
pretty_env_logger = "0.4"

[build-dependencies]
rustc_tools_util = "0.2"
