[package]
name = "wasmrun"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2.33.3"
libwasmrun = { path = "../libwasmrun" }

[build-dependencies]
rustc_tools_util = "0.2.0"
