[package]
name = "w4wr"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
libwasmrun = { path = "../libwasmrun" }
pixels = "0.13.0"
winit = "0.28"
winit_input_helper = "0.14"
