name: CI

on: [push, pull_request]

jobs:
  run_tests:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true

      - name: Build
        run: cargo build

      - name: Download wast2json
        run: |
            wget https://github.com/WebAssembly/wabt/releases/download/1.0.19/wabt-1.0.19-ubuntu.tar.gz
            tar -vxf wabt-1.0.19-ubuntu.tar.gz
            cp wabt-1.0.19/bin/wast2json .

      - name: Run tests
        run: |
            export PATH=`pwd`:$PATH
            git submodule update --init --recursive
            cargo run --bin spec-test || true
            diff -u test_output_current test_output

      - name: Check formatting
        run: cargo fmt --all -- --check
