name: CI

on: [push, pull_request]

jobs:
  run_tests:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Build
        run: cargo build

      - name: Run tests
        run: |
            pwd
            ls -lha .
            ls -lha target
            ls -lha target/debug
            ls -lha tests
            file target/debug/spec-test
            ./target/debug/spec-test tests/spec.wast # cargo run doesn't work here???

      - name: Check formatting
        run: cargo fmt --all -- --check
