name: CI

on: [push, pull_request]

jobs:
  unit_tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Run unit tests
        run: cargo test

  spec_tests:
    name: 'Run WebAssembly test suite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Build wast2json
        run: |
            sudo apt-get update
            sudo apt-get install cmake
            bash ci/build_wabt.sh

      - name: Run spec tests
        run: |
            export PATH=`pwd`:$PATH
            git submodule update --init --recursive
            cargo run --bin spec-test

  # wasi_tests:
  #   name: 'Run WASI tests'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Get Rust stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #           toolchain: stable
  #           target: wasm32-wasi
  #           override: true
  #
  #     - name: Get wasmtime
  #       run: bash ci/get_wasmtime.sh
  #
  #     - name: Build
  #       run: cargo build
  #
  #     - name: Run tests
  #       run: |
  #           export PATH=`pwd`:$PATH
  #           cargo run --bin wasi-test

  formatting:
    name: 'Check formatting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true

      - name: Check formatting
        run: cargo fmt --all -- --check
